### ISSUE TITLE
Acoustic based transit gotcha

### ISSUE THREAD

**Issue by viron11111** [uf-mil/Navigator#137]
The rules give an example of the pinger mission where the boat drives through one gate, circles a buoy, and then drives back through another gate (page 19, http://robotx.org/images/files/2016-MRC-Tasks-2016-11-03.pdf).  We'll have to be careful with how we define this mission since the pinger mission cannot be dependent on itself (ie, running a pinger mission immediately after a pinger mission, pinger mission dependent on pinger mission).  Recommend breaking the mission into three parts: pinger mission, circle mission, pinger mission.  Thoughts?

**Comment by tessbianchi** [comment]
I think this should just be one big mission.

**Comment by viron11111** [comment]
Roger.  Did we run this type of mission the weekend?

**Comment by mattlangford** [comment]
We ran the pinger mission by itself on both sides of the gate, @ironmig says he set up code to circle the next totem we find.

**Comment by ironmig** [comment]
I don't believe we will ever go through one gate and return through another. In quals, you go through the gate with the pinger, circle a totem 30 meters off, then go back through the same gate. In finals, you go through the correct gate to begin your run (instead of speed gate) and exit through the same gate to end.

**Comment by viron11111** [comment]
Roger.
