### ISSUE TITLE
Scan the code firmware: repeat pattern for n seconds

### ISSUE THREAD

**Issue by ironmig** [uf-mil/NaviGator#281]
As we discussed in the meeting, update the arduino code for scan the code to loop in the following way
* Randomly select 3 colors (out of Red, Green, Blue, Yellow) to flash
* Flash that pattern (1 second per color, one second off) for n seconds
* repeat

This will allow us to test multiple patterns without reprogramming the arduino, but still have a pattern stay on long enough to test.

**Comment by yikaimao** [comment]
the LED panel is now updated with new code.
some potential problems:
1. delay is not exactly 1 sec long, feels a little bit longer(not sure why but I have to use delay(2000) instead of delay(1000) to get about 1s delay)
2. yellow is too bright, looks like white(now using 4-bit color mode, change RGB to (15, 10,0) is a little bit better)
3. old code draw each pixel one by one, new code uses the matrix.fillScreen() function. (maybe slower, maybe faster, needs to be tested by the new camera)

**Comment by ironmig** [comment]
Cool it does look better! However I see a significant delay between displaying colors in the same sequence. It should go RED GREEN BLUE OFF with no off in between colors. I'm also not seeing the change described in the issue, which is to display the same sequence several times before switching.
![bluee](https://user-images.githubusercontent.com/9502636/35174396-3d4df934-fd3d-11e7-868a-3f50ebc9e01a.png)

**Comment by yikaimao** [comment]
My bad, i read the rules wrong. I thought there should be 1s off between each color, I’ll remove the delay! 
How many times you want to repeat the same pattern? 3 maybe?

**Comment by yikaimao** [comment]
Also can you distinguish between yellow and green from the camera image? I can display characters on the panel so if you want more functions just let me know

**Comment by ironmig** [comment]
Yes yellow and green are distinct. I'd say repeat a pattern 5 times.

**Comment by ironmig** [comment]
Thanks @yikaimao! this is done.
